python kitti_sparsify.py --slice 2 --data_mode training --multi_lidar --sampling_num3 --sparse_lidar_save_path ./sparse_lidar_results/multi_downsampling_sampling_3
python kitti_sparsify.py --slice 2 --data_mode testing --multi_lidar --sampling_num3 --sparse_lidar_save_path ./sparse_lidar_results/multi_downsampling_sampling_3
python kitti_sparsify.py --slice 4 --data_mode training --multi_lidar --sampling_num3 --sparse_lidar_save_path ./sparse_lidar_results/multi_downsampling_sampling_3
python kitti_sparsify.py --slice 4 --data_mode testing --multi_lidar ---sampling_num3 --sparse_lidar_save_path ./sparse_lidar_results/multi_downsampling_sampling_3
python kitti_sparsify.py --slice 8 --data_mode training --multi_lidar --sampling_num3 --sparse_lidar_save_path ./sparse_lidar_results/multi_downsampling_sampling_3
python kitti_sparsify.py --slice 8 --data_mode testing --multi_lidar --sampling_num3 --sparse_lidar_save_path ./sparse_lidar_results/multi_downsampling_sampling_3
python kitti_sparsify.py --slice 16 --data_mode training --multi_lidar --sampling_num3 --sparse_lidar_save_path ./sparse_lidar_results/multi_downsampling_sampling_3
python kitti_sparsify.py --slice 16 --data_mode testing --multi_lidar --sampling_num3 --sparse_lidar_save_path ./sparse_lidar_results/multi_downsampling_sampling_3
python kitti_sparsify.py --slice 32 --data_mode training --multi_lidar --sampling_num3 --sparse_lidar_save_path ./sparse_lidar_results/multi_downsampling_sampling_3
python kitti_sparsify.py --slice 32 --data_mode testing --multi_lidar --sampling_num3 --sparse_lidar_save_path ./sparse_lidar_results/multi_downsampling_sampling_3